import { Inter } from 'next/font/google'
import './globals.css'
import Container from '@/component/Container/container'
import Home from '@/component/Home/home'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Container>
        {children}
        <Home/>
        </Container>
        </body>
    </html>
  )
}
